/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tml Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.TmlIdentifier#getValue <em>Value</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.TmlIdentifier#getTml <em>Tml</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getTmlIdentifier()
 * @model
 * @generated
 */
public interface TmlIdentifier extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(TmlIdentifier)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getTmlIdentifier_Value()
   * @model containment="true"
   * @generated
   */
  TmlIdentifier getValue();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.TmlIdentifier#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(TmlIdentifier value);

  /**
   * Returns the value of the '<em><b>Tml</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tml</em>' attribute.
   * @see #setTml(String)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getTmlIdentifier_Tml()
   * @model
   * @generated
   */
  String getTml();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.TmlIdentifier#getTml <em>Tml</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tml</em>' attribute.
   * @see #getTml()
   * @generated
   */
  void setTml(String value);

} // TmlIdentifier
